=== Anditenriwali/WEBSERVICE/tugas/src/tugas/pend.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="kependidikan">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="mahasiswa"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="mahasiswa">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nama"/>
                <xs:element ref="Npm" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="Prodi"/>
                <xs:element ref="asal"/>
                <xs:element ref="orangtua"/>
                <xs:element ref="agama"/>
                <xs:element ref="ttl"/>
                <xs:element ref="no.telp"/>
                <xs:element ref="semester"/>
                <xs:element ref="ipk"/>
            </xs:sequence>
            <xs:attribute name="status" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="nama" type="xs:string"/>
    <xs:element name="Npm" type="xs:integer"/>
    <xs:element name="Prodi" type="xs:string"/>
    <xs:element name="asal">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Kota"/>
                <xs:element ref="kodepos"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Kota" type="xs:NCName"/>
    <xs:element name="kodepos" type="xs:integer"/>
    <xs:element name="orangtua">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ayah"/>
                <xs:element ref="ibu"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ayah" type="xs:string"/>
    <xs:element name="ibu" type="xs:NCName"/>
    <xs:element name="agama" type="xs:NCName"/>
    <xs:element name="ttl" type="xs:string"/>
    <xs:element name="no.telp" type="xs:integer"/>
    <xs:element name="semester" type="xs:integer"/>
    <xs:element name="ipk">
    	<xs:simpleType>
    		<xs:restriction base="xs:integer">
    			<xs:pattern value="3"></xs:pattern>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
</xs:schema>

=== Anditenriwali/WEBSERVICE/tugas/bin/tugas/Pend.xml
<?xml version="1.0" encoding="UTF-8"?>
<kependidikan  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pend.xsd">

<mahasiswa status="aktif">
<nama>Andi Tenri Wali</nama>
<Npm>1154013</Npm>
<Prodi>D4 TI 2C</Prodi>
<asal>
		<Kota>Bandung</Kota>
		<kodepos>40552</kodepos>
</asal>
<orangtua>
	<ayah>Andi Bintang Raja</ayah>
	<ibu> Rubaedah </ibu>
</orangtua>
<agama>Islam</agama>
<ttl>tanete,12 januari 1997</ttl>
<no.telp>081234567899</no.telp>
<semester>4</semester>
<ipk>3</ipk>
</mahasiswa>

<mahasiswa status="aktif">
<nama>Andi Nurfadillah ali</nama>
<Npm>1154011</Npm>
<Prodi>D4 TI 2C</Prodi>
<asal>
		<Kota>Bandung</Kota>
		<kodepos>40552</kodepos>
</asal>
<orangtua>
	<ayah>Andi Ali</ayah>
	<ibu> Rosmi </ibu>
</orangtua>
<agama>Islam</agama>
<ttl>herlang,13 januari 1997</ttl>
<no.telp>081234567888</no.telp>
<semester>4</semester>
<ipk>3</ipk>
</mahasiswa>

<mahasiswa status="aktif">
<nama>Arya niken</nama>
<Npm>1154022</Npm>
<Prodi>D4 TI 2C</Prodi>
<asal>
		<Kota>Bandung</Kota>
		<kodepos>40552</kodepos>
</asal>
<orangtua>
	<ayah>vidi aldiano</ayah>
	<ibu> maudy</ibu>
</orangtua>
<agama>Islam</agama>
<ttl>bekasi,14 januari 1997</ttl>
<no.telp>081234567877</no.telp>
<semester>4</semester>
<ipk>3</ipk>
</mahasiswa>

<mahasiswa status="aktif">
<nama>pebridayanti</nama>
<Npm>1154010</Npm>
<Prodi>D4 TI 2C</Prodi>
<asal>
		<Kota>Bandung</Kota>
		<kodepos>40552</kodepos>
</asal>
<orangtua>
	<ayah>sehun</ayah>
	<ibu>irene</ibu>
</orangtua>
<agama>Islam</agama>
<ttl>medan,12 januari 1997</ttl>
<no.telp>081234567866</no.telp>
<semester>4</semester>
<ipk>3</ipk>
</mahasiswa>

<mahasiswa status="aktif">
<nama>ananda</nama>
<Npm>1154088</Npm>
<Prodi>D4 TI 2C</Prodi>
<asal>
		<Kota>Bandung</Kota>
		<kodepos>40552</kodepos>
</asal>
<orangtua>
	<ayah>Kai</ayah>
	<ibu>Krystal</ibu>
</orangtua>
<agama>Islam</agama>
<ttl>tiro,19 januari 1997</ttl>
<no.telp>081234567887</no.telp>
<semester>4</semester>
<ipk>3</ipk>
</mahasiswa>

</kependidikan>
